### ISSUE TITLE
Problems with vi editing mode

### ISSUE THREAD

**Issue by Aster89** [codekitchen/pipeline#7] opened 2020-02-20 21:24 UTC
First of all, thank you for this "small" useful tool, which I read from [here](https://stackoverflow.blog/2020/02/12/when-laziness-is-efficient-make-the-most-of-your-command-line/) a few minutes ago for the first time.

Thanks to my habit of using `vi` editing mode in `bash`, I'm quick enough in command line editing and history navigation, however your tool can make a difference in doing it, especially when it comes to answering some `sed`/`awk`/`grep`/... related question of StackOverflow, for instance.

Unfortunately there are some bit which prevent a productive use with the `set editing-mode vi` setting in `.inputrc`.

When that option is set, hitting enter when in command mode (this happens frequently, if you finished the edit by pressing <kbd>Escape</kbd>, <kbd>D</kbd>, <kbd>x</kbd>, or any <kbd>d</kbd>-command) exits `pipeline` by leaving the terminal cluttered.

Terminal emulator: [`urxvt`](https://wiki.archlinux.org/index.php/Rxvt-unicode)
```
$ bash --version | head -2
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
```

Please, find attached at the bottom a terminal screencast demonstrating the issue.

I've noticed also other issues, which are possibly (and hopefully) all related to a common underline flaw (or, more hopefully, to some configuration of mine which conflicts with the program?):

- If I type just `echo`, but also if I type `echo ''`, and hit <kbd>Enter</kbd> the line gets printed; I suspected this might be related to the zero-lines-of-output, but this is unlikely, as `echo -e 'a\nb\nc' | sed -n '/d/p'` works fine.
- This sounds a bit vudù to me, but if I remove the option `set editing-mode vi` line from my `.inputrc`, open a new terminal, and I hit <kbd>Escape</kbd> then <kbd>Enter</kbd>... the editing mode changes to `vi`, for that session of `pipeline`!

For all the above, if it helps, I can make screencasts demonstrating the issue.

[![asciicast](https://asciinema.org/a/ljrVWJVyaDqnYwHIFVUAV23oo.svg)](https://asciinema.org/a/ljrVWJVyaDqnYwHIFVUAV23oo)

**Comment by codekitchen** [comment] 2020-02-21 16:39
Oh I was wondering about all the new stars, thanks for the link.

The problem with `echo ''` looks like a simple bug when the output is just a single newline, I've created a separate issue for that here: https://github.com/codekitchen/pipeline/issues/8

I'll play with vi editing-mode on Linux to try and figure out what's going on there, .inputrc isn't honored on MacOS since pipeline uses libedit rather than libreadline on that platform. Thanks for the screencast, that's really helpful.

**Comment by Aster89** [comment] 2020-02-21 17:51
Curisity: have you been able to reproduce my second bullet point?

**Comment by codekitchen** [comment] 2020-02-21 18:35
Yeah, I can reproduce both the exit-on-enter issue and the strange switch-to-vi-mode bullet point on Ubuntu 19.10 while ssh'd in using iTerm2. The latter issue must be some behavior of readline that I wasn't aware of until now -- if you add `set show-mode-in-prompt on` to your `.inputrc`, you can see how readline is changing the editing mode to vi (ins) mode after pressing <kbd>Escape</kbd> then <kbd>Enter</kbd>. This doesn't seem to happen in bash itself, I'm not sure why. However I've confirmed that the same behavior exists in other programs that use readline, such as the `pry` REPL for ruby. So I think it's out of my hands.

I'm still looking into why the first issue happens, the way that `pipeline` overrides the behavior of pressing enter when using readline is definitely a bit unusual.

**Comment by codekitchen** [comment] 2020-02-22 02:33
This has been fixed on master, thanks for the detailed report!

**Closed as completed** 2020-02-22 02:33 UTC
